# Generated by Django 5.1.2 on 2024-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='fichiers/'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='adresse',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
    ]
