# Generated by Django 5.1.2 on 2024-11-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichier_csv', '0002_fichier_file_alter_fichier_adresse_alter_fichier_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='nom',
        ),
    ]
