# Generated by Django 5.1.2 on 2024-11-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier_csv', '0003_remove_fichier_adresse_remove_fichier_nom'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='projet',
        ),
        migrations.AddField(
            model_name='fichier',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='sites.sites'),
        ),
    ]
