# Generated by Django 5.1.2 on 2024-11-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier_csv', '0005_client_donneesannuelles_donneesmensuelles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorie_tarifaire',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='niveau_tension',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
