# Generated by Django 5.1.2 on 2024-11-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier_csv', '0007_alter_client_categorie_tarifaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneesmensuelles',
            name='donnees_annuelles',
        ),
        migrations.RemoveField(
            model_name='client',
            name='site',
        ),
        migrations.AddField(
            model_name='donneesmensuelles',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneesmensuelles',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donnees_mensuelles', to='fichier_csv.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donneesmensuelles',
            name='energie_reactive',
            field=models.FloatField(verbose_name='Énergie Réactive (kWh)'),
        ),
        migrations.AlterField(
            model_name='donneesmensuelles',
            name='puissance_max_releve',
            field=models.FloatField(verbose_name='Puissance Max Relevée (kWh)'),
        ),
        migrations.DeleteModel(
            name='DonneesAnnuelles',
        ),
    ]
