# Generated by Django 5.1.2 on 2024-11-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier_csv', '0008_remove_donneesmensuelles_donnees_annuelles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='file',
        ),
        migrations.RemoveField(
            model_name='donneesmensuelles',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='donneesmensuelles',
            name='client',
        ),
        migrations.CreateModel(
            name='DonneesAnnuelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fichier_csv.client')),
            ],
        ),
        migrations.AddField(
            model_name='donneesmensuelles',
            name='Annuelles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donnees_mensuelles', to='fichier_csv.donneesannuelles'),
            preserve_default=False,
        ),
    ]
