# Generated by Django 5.1.2 on 2024-11-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier_csv', '0009_remove_client_file_remove_donneesmensuelles_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneesmensuelles',
            name='mois',
            field=models.CharField(max_length=100),
        ),
    ]
