# Generated by Django 5.1.2 on 2024-11-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier_csv', '0010_alter_donneesmensuelles_mois'),
        ('projet', '0002_projet_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='fichier_csv.client'),
        ),
    ]
