# Generated by Django 5.1.2 on 2024-11-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_alter_projet_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='client',
        ),
    ]
